version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./shared-outputs:/app/shared-outputs
    networks:
      - optormc_net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    volumes:
      - ./shared-outputs:/app/shared-outputs
    networks:
      - optormc_net

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama/models
    networks:
      - optormc_net

volumes:
  ollama-models:

networks:
  optormc_net:
    driver: bridge
