version: '3.8'

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - optormc_net

  frontend:
    build:
      context: ./frontend
      target: deps
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./shared-outputs:/app/shared-outputs
    networks:
      - optormc_net

  backend:
    build: ./backend
    depends_on:
      - ollama
    volumes:
      - ./shared-outputs:/app/shared-outputs
    networks:
      - optormc_net

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama/models
    networks:
      - optormc_net

volumes:
  ollama-models:

networks:
  optormc_net:
    driver: bridge
